### ISSUE TITLE
添加类似Dragablz的分窗的功能

### ISSUE THREAD

**Issue by yijie0110** [sanshiliuxiao/DivergenceMeter#2]
最近也在研究这个东西,有没有兴趣添加[Dragablz](https://github.com/ButchersBoy/Dragablz) 的功能?
我看了两个示例怎么也写不出来:
https://github.com/codingdna2/EdgeDragablz
https://github.com/svantreeck/DragablzPrism

想用handycontrol 的Tabcontrol加上Dragablz 实现拖拽和切换功能.

**Comment by sanshiliuxiao** [comment]
不考虑，这个项目已经结束了 （^_^）

**Comment by yijie0110** [comment]
好家伙, 我今天才看到我issue 发错项目了 应该是发到这个项目下的 😂[PrismRegionWithHcTabControl](https://github.com/sanshiliuxiao/PrismRegionWithHcTabControl)

**Comment by sanshiliuxiao** [comment]
> 好家伙, 我今天才看到我issue 发错项目了 应该是发到这个项目下的 😂[PrismRegionWithHcTabControl](https://github.com/sanshiliuxiao/PrismRegionWithHcTabControl) 不过没事了.我大概把我的拖拽tabcontrol解决了

优秀！！！
